#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "config",
    srcs = [
        "config.cpp",
        "packs.cpp",
        "update.cpp",
    ],
    header_namespace = "osquery/config",
    exported_headers = [
        "config.h",
    ],
    link_whole = True,
    tests = [
        osquery_target("osquery/config/tests:config"),
        osquery_target("osquery/config/tests:packs"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery:headers"),
        osquery_target("osquery/filesystem:filesystem"),
        osquery_target("osquery/hashing:hashing"),
        osquery_target("osquery/utils:utils"),
        osquery_target("osquery/utils/system:time"),
        osquery_tp_target("googletest", "gtest"),
    ],
)
