#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "config",
    srcs = [
        "config.cpp",
        "packs.cpp",
        "config_plugin.cpp",
        "config_parser_plugin.cpp",
    ],
    header_namespace = "osquery/config",
    exported_headers = [
        "config.h",
        "config_plugin.h",
        "config_parser_plugin.h",
    ],
    link_whole = True,
    tests = [
        osquery_target("osquery/config/tests:config_tests"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery:headers"),
        osquery_target("osquery/filesystem:osquery_filesystem"),
        osquery_target("osquery/hashing:hashing"),
        osquery_target("osquery/utils:utils"),
        osquery_target("osquery/utils/system:time"),
    ],
)
