#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed in accordance with the terms specified in
#  the LICENSE file found in the root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "schemer_json",
    header_namespace = "osquery/utils/schemer/json",
    exported_headers = [
        "schemer_json.h",
        "schemer_json_error.h",
        "schemer_json_impl.h",
    ],
    tests = [
        osquery_target("osquery/utils/schemer/json/tests:schemer_json_tests"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/utils/expected:expected"),
        osquery_target("osquery/utils/json:json"),
        osquery_target("osquery/utils/schemer:schemer"),
        osquery_tp_target("rapidjson"),
    ],
)
