#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

# @generated

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_prebuilt_cxx_library")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_tp_prebuilt_cxx_library(
    name = "bzip2",
    platforms = [
        "linux-x86_64",
        "windows-x86_64",
    ],
    sha256sums = {
        "linux-x86_64": "1cc3eaf8fe78f19fcae9f71065b04bd2dedb4862081f1d1c96e0668f3df864c8",
        "windows-x86_64": "11001b5e353bc255a755284b9ed8baed01b6d9fe2a63e5e325124e8b998d48c2",
    },
    platform_static_libs = {
        "linux-x86_64": [
            "lib/libbz2.a",
        ],
        "windows-x86_64": [
            "lib/libbz2.lib",
        ],
    },
    linker_flags = [

    ],
    deps = [

    ],
    version = "1.0.6",
    build = "0",
    visibility = ["PUBLIC"],
)
