# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# We run out of memory on the RTD builder.
submodules:
  exclude: all
