#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "filesystem_config",
    srcs = [
        "filesystem_config.cpp",
    ],
    link_whole = True,
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/config:config"),
        osquery_target("osquery/utils/config:config"),
    ],
)

osquery_cxx_library(
    name = "tls_config",
    srcs = [
        "tls_config.cpp",
    ],
    header_namespace = "osquery/config/plugins",
    exported_headers = [
        "tls_config.h",
    ],
    link_whole = True,
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/config:config"),
        osquery_target("osquery/remote:requests"),
        osquery_target("osquery/remote:utility"),
        osquery_target("osquery/remote/serializers:json"),
    ],
)
