#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_test(
    name = "plugin_sdk_tests",
    srcs = [
        "registry_tests.cpp",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/extensions:impl_thrift"),
        osquery_target("osquery/sdk:plugin_sdk"),
    ],
)
