#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "info",
    srcs = [
        "platform_type.cpp",
        "tool_type.cpp",
        "version.cpp",
    ],
    header_namespace = "osquery/utils/info",
    exported_headers = [
        "platform_type.h",
        "tool_type.h",
        "version.h",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_target("osquery/utils/macros:macros"),
    ],
)
