#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "numeric_monitoring_filesystem",
    srcs = [
        "filesystem.cpp",
    ],
    header_namespace = "plugins/numeric_monitoring",
    exported_headers = [
        "filesystem.h",
    ],
    link_whole = True,
    tests = [
        osquery_target("plugins/numeric_monitoring/tests:numeric_monitoring_filesystem_tests"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/filesystem:osquery_filesystem"),
        osquery_target("osquery/numeric_monitoring:numeric_monitoring"),
    ],
)
