#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed in accordance with the terms specified in
#  the LICENSE file found in the root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "events_stream_registry",
    srcs = [
        "events_stream_registry.cpp",
    ],
    header_namespace = "osquery/experimental/events_stream",
    exported_headers = [
        "events_stream_registry.h",
    ],
    link_whole = True,
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/utils:utils"),
        osquery_tp_target("boost"),
    ],
)

osquery_cxx_library(
    name = "events_stream",
    srcs = [
        "events_stream.cpp",
    ],
    header_namespace = "osquery/experimental/events_stream",
    exported_headers = [
        "events_stream.h",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/experimental/events_stream:events_stream_registry"),
        osquery_target("osquery/core:core"),
        osquery_target("osquery/utils:utils"),
        osquery_tp_target("boost"),
    ],
)
