#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "utility_table",
    srcs = [
        "file.cpp",
        "osquery.cpp",
        "time.cpp",
    ],
    header_namespace = "osquery/tables/utility",
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/config:config"),
        osquery_target("osquery/core:core"),
        osquery_target("osquery/filesystem:osquery_filesystem"),
        osquery_target("osquery/process:process"),
        osquery_target("osquery/utils/macros:macros"),
        osquery_target("osquery/utils/system:system_utils"),
        osquery_tp_target("boost"),
    ],
)
