#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "helper",
    srcs = [
        "test_util.cpp",
    ],
    header_namespace = "osquery/tests/",
    exported_headers = [
        "test_util.h",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/filesystem:osquery_filesystem"),
        osquery_target("osquery/process:process"),
        osquery_target("osquery/remote/serializers:serializer_json"),
        osquery_target("osquery/sql:sql"),
        osquery_target("osquery/utils:utils"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_target("osquery/utils/system:time"),
        osquery_target("plugins/database:ephemeral"),
        osquery_target("specs:tables"),
        osquery_tp_target("boost"),
        osquery_tp_target("googletest", "gtest_headers"),
    ],
)
