#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:platforms.bzl", "FREEBSD")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "sleuthkit_table",
    srcs = [
        "sleuthkit.cpp",
    ],
    exported_post_platform_linker_flags = [
        (
            FREEBSD,
            [
                "-ltsk",
            ],
        ),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery:headers"),
        osquery_target("osquery/hashing:hashing"),
        osquery_target("osquery/logger:logger"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_tp_target("sleuthkit"),
    ],
)
