#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")

osquery_cxx_library(
    name = "macros",
    header_namespace = "osquery/utils/macros",
    exported_headers = [
        "macros.h",
    ],
    visibility = ["PUBLIC"],
)
