#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:platforms.bzl", "MACOSX")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "tls_enroll",
    srcs = [
        "enroll.cpp",
        "tls_enroll.cpp",
    ],
    header_namespace = "osquery/remote/enroll",
    exported_headers = [
        "tls_enroll.h",
    ],
    link_whole = True,
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/process:process"),
        osquery_target("osquery/remote:http_client"),
        osquery_target("osquery/remote:requests"),
        osquery_target("osquery/remote/serializers:serializer_json"),
        osquery_target("osquery/remote/transports:transports_tls"),
        osquery_target("osquery/utils/json:json"),
        osquery_target("osquery/utils/system:time"),
        osquery_tp_target("boost"),
    ],
)

osquery_cxx_test(
    name = "remote_enroll_tests",
    srcs = [
        "tests/enroll_tests.cpp",
    ],
    env = {
        "TEST_CONF_FILES_DIR": "$(location {})".format(
            osquery_target("tools/tests:test_files"),
        ),
    },
    platform_srcs = [
        (
            MACOSX,
            ["tests/plugins/tls_enroll_tests.cpp"],
        ),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/config/tests:test_utils"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/events:events"),
        osquery_target("osquery/extensions:extensions"),
        osquery_target("osquery/extensions:impl_thrift"),
        osquery_target("osquery/process:process"),
        osquery_target("osquery/remote/enroll:tls_enroll"),
        osquery_target("osquery/remote/tests:remote_test_utils"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_target("osquery/utils/info:info"),
        osquery_target("plugins/config:tls_config"),
        osquery_target("plugins/database:ephemeral"),
        osquery_target("plugins/killswitch:killswitch_filesystem"),
        osquery_target("tests:helper"),
    ],
)
