#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "debug",
    header_namespace = "osquery/utils/debug",
    exported_headers = [
        "debug_only.h",
    ],
    tests = [":debug_tests"],
    visibility = ["PUBLIC"],
    deps = [
        osquery_tp_target("boost"),
    ],
)

osquery_cxx_test(
    name = "debug_tests",
    srcs = [
        "tests/debug_only.cpp",
    ],
    visibility = ["PUBLIC"],
    deps = [
        ":debug",
    ],
)
