#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "registry",
    srcs = [
        "registry_factory.cpp",
        "registry_interface.cpp",
    ],
    tests = [
        osquery_target("osquery/registry/tests:registry_tests"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery:headers"),
        osquery_target("osquery/core:core"),
        osquery_target("osquery/process:process"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_target("osquery/utils/system:env"),
        osquery_tp_target("boost"),
    ],
)
