#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_test(
    name = "sqlite_plugin_tests",
    srcs = [
        "sqlite.cpp",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/dispatcher:dispatcher"),
        osquery_target("osquery/events:events"),
        osquery_target("osquery/extensions:extensions"),
        osquery_target("osquery/extensions:impl_thrift"),
        osquery_target("osquery/registry:registry"),
        osquery_target("osquery/remote/enroll:tls_enroll"),
        osquery_target("osquery/utils/json:json"),
        osquery_target("plugins/config:tls_config"),
        osquery_target("plugins/database:ephemeral"),
        osquery_target("plugins/database:sqlite_plugin"),
        osquery_target("specs:tables"),
        ":database_test_utils",
    ],
)

osquery_cxx_test(
    name = "rocksdb_tests",
    srcs = [
        # "rocksdb.cpp", # TODO: it is failing :(
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/dispatcher:dispatcher"),
        osquery_target("osquery/events:events"),
        osquery_target("osquery/extensions:extensions"),
        osquery_target("osquery/extensions:impl_thrift"),
        osquery_target("osquery/registry:registry"),
        osquery_target("osquery/remote/enroll:tls_enroll"),
        osquery_target("osquery/utils/json:json"),
        osquery_target("plugins/config:tls_config"),
        osquery_target("plugins/database:ephemeral"),
        osquery_target("plugins/database:rocksdb_plugin"),
        osquery_target("specs:tables"),
        ":database_test_utils",
    ],
)

osquery_cxx_library(
    name = "database_test_utils",
    srcs = [
        "utils.cpp",
    ],
    header_namespace = "plugins/database/tests",
    exported_headers = [
        "utils.h",
    ],
    deps = [
        osquery_target("osquery/filesystem:osquery_filesystem"),
        osquery_target("osquery/utils/json:json"),
        osquery_tp_target("googletest", "gtest_headers"),
    ],
)
