#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "distributed",
    srcs = ["distributed.cpp"],
    tests = [
        osquery_target("osquery/distributed/tests:distributed_tests"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/core/plugins:plugins"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/logger:logger"),
        osquery_target("osquery/utils/json:json"),
        osquery_target("osquery/utils/system:time"),
    ],
)
