#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed in accordance with the terms specified in
#  the LICENSE file found in the root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "schemer",
    header_namespace = "osquery/utils/schemer",
    exported_headers = [
        "schemer.h",
    ],
    tests = [
        osquery_target("osquery/utils/schemer/tests:schemer_tests"),
    ],
    visibility = ["PUBLIC"],
)
