#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed in accordance with the terms specified in
#  the LICENSE file found in the root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:platforms.bzl", "LINUX")

osquery_cxx_library(
    name = "syscalls_tracing",
    srcs = [
        "syscalls_tracing.cpp",
    ],
    header_namespace = "osquery/experimental/tracing",
    exported_headers = [
        "syscalls_tracing.h",
    ],
    platform_headers = [
        (
            LINUX,
            [
                "syscalls_tracing_impl.h",
            ],
        ),
    ],
    platform_srcs = [
        (
            LINUX,
            [
                "syscalls_tracing_impl.cpp",
            ],
        ),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/dispatcher:dispatcher"),
        osquery_target("osquery/experimental/tracing/linux:probes_events"),
        osquery_target("osquery/experimental/events_stream:events_stream"),
        osquery_target("osquery/utils/caches:lru"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_target("osquery/utils/json:json"),
        osquery_target("osquery/utils/system/linux/proc:proc"),
        osquery_target("osquery/utils/system:time"),
    ],
)
