#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

load("//tools/build_defs/oss/osquery:native.bzl", "osquery_filegroup")
load("//tools/build_defs/oss/osquery:python.bzl", "osquery_python_library")

osquery_python_library(
    name = "utils",
    srcs = [
        "utils.py",
    ],
    base_module = "osquery.tools.tests",
    visibility = ["PUBLIC"],
)

osquery_filegroup(
    name = "conf_files",
    srcs = glob([
        "*.conf",
    ]),
    visibility = ["PUBLIC"],
)

osquery_filegroup(
    name = "config_files",
    srcs = glob([
        "*.config",
    ]),
    visibility = ["PUBLIC"],
)

osquery_filegroup(
    name = "plist_files",
    srcs = glob([
        "*.plist",
    ]),
    visibility = ["PUBLIC"],
)

osquery_filegroup(
    name = "test_files",
    srcs = glob([
        "*",
    ]),
    visibility = ["PUBLIC"],
)

osquery_filegroup(
    name = "aws_files",
    srcs = glob([
        "aws/*",
    ]),
    visibility = ["PUBLIC"],
)
