#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:python.bzl", "osquery_python_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_filegroup")

osquery_python_library(
    name = "tools_test_utils",
    srcs = [
        "utils.py",
    ],
    base_module = "osquery_tests.tools.tests",
    visibility = ["PUBLIC"],
)

osquery_filegroup(
    name = "python_script_files",
    srcs = glob([
        "*.py",
    ]),
    visibility = ["PUBLIC"],
)
