#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "error",
    header_namespace = "osquery/utils/error",
    exported_headers = [
        "error.h",
    ],
    tests = [":error_tests"],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/utils/conversions:to"),
        osquery_target("osquery/utils:attribute"),
    ],
)

osquery_cxx_test(
    name = "error_tests",
    srcs = [
        "tests/error.cpp",
    ],
    visibility = ["PUBLIC"],
    deps = [
        ":error",
    ],
)
