#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_test(
    name = "yara_tests",
    srcs = [
        "yara_tests.cpp",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/tables/yara:yara"),
        osquery_target("osquery/core:core"),
        osquery_target("osquery/filesystem:filesystem"),
        osquery_target("osquery/remote:http_client"),
        osquery_target("osquery/utils:utils"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_target("osquery/tables/system:system"),
        osquery_target("osquery/config/tests:test_utils"),
        osquery_target("osquery/remote/tests:remote_test_utils"),
        osquery_target("osquery/filesystem:filesystem"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/database/plugins:ephemeral"),
        osquery_tp_target("boost"),
    ],
)
