#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "serializer_json",
    srcs = ["json.cpp"],
    header_namespace = "osquery/remote/serializers",
    exported_headers = ["json.h"],
    tests = [":remote_json_serializers_tests"],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/remote:requests"),
        osquery_target("osquery/utils/json:json"),
        osquery_tp_target("boost"),
    ],
)

osquery_cxx_test(
    name = "remote_json_serializers_tests",
    srcs = [
        "tests/json_serializers_tests.cpp",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/remote/serializers:serializer_json"),
    ],
)
