#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "lru",
    header_namespace = "osquery/utils/caches",
    exported_headers = [
        "lru.h",
        "lru-impl.h",
    ],
    tests = [
        osquery_target("osquery/utils/caches/tests:lru_tests"),
    ],
    visibility = ["PUBLIC"],
)
