#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")

osquery_cxx_library(
    name = "config",
    srcs = [
        "default_paths.cpp",
    ],
    header_namespace = "osquery/utils/config",
    exported_headers = [
        "default_paths.h",
    ],
    visibility = ["PUBLIC"],
)
