#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")

osquery_cxx_library(
    name = "utils_config",
    srcs = [
        "default_paths.cpp",
    ],
    header_namespace = "osquery/utils/config",
    exported_headers = [
        "default_paths.h",
    ],
    visibility = ["PUBLIC"],
)
