#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:platforms.bzl", "LINUX", "MACOSX", "POSIX", "WINDOWS")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "main",
    srcs = [
        "main.cpp",
    ],
    header_namespace = "osquery/main",
    exported_headers = [
        "main.h",
    ],
    platform_deps = [
        (
            LINUX,
            [
                osquery_target("osquery/logger/plugins:aws_firehose"),
                osquery_target("osquery/logger/plugins:aws_kinesis"),
                osquery_target("osquery/logger/plugins:aws_log_forwarder"),
                osquery_target("osquery/logger/plugins:kafka_producer"),
            ],
        ),
        (
            MACOSX,
            [
                osquery_target("osquery/logger/plugins:aws_firehose"),
                osquery_target("osquery/logger/plugins:aws_kinesis"),
                osquery_target("osquery/logger/plugins:aws_log_forwarder"),
                osquery_target("osquery/logger/plugins:kafka_producer"),
            ],
        ),
        (
            WINDOWS,
            [
                osquery_target("osquery/logger/plugins:aws_firehose"),
                osquery_target("osquery/logger/plugins:aws_kinesis"),
                osquery_target("osquery/logger/plugins:aws_log_forwarder"),
                osquery_target("osquery/logger/plugins:windows_event_log"),
            ],
        ),
    ],
    platform_srcs = [
        (
            POSIX,
            [
                "posix/main.cpp",
            ],
        ),
        (
            WINDOWS,
            [
                "windows/main.cpp",
            ],
        ),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery:headers"),
        osquery_target("osquery/config/parsers:parsers"),
        osquery_target("osquery/config/plugins:filesystem_config"),
        osquery_target("osquery/config/plugins:tls_config"),
        osquery_target("osquery/core:core"),
        osquery_target("osquery/core/plugins:plugins"),
        osquery_target("osquery/core/sql:sql"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/database/plugins:ephemeral"),
        osquery_target("osquery/database/plugins:rocksdb"),
        osquery_target("osquery/database/plugins:sqlite"),
        osquery_target("osquery/devtools:devtools"),
        osquery_target("osquery/dispatcher:dispatcher"),
        osquery_target("osquery/distributed/plugins:tls"),
        osquery_target("osquery/extensions:extensions"),
        osquery_target("osquery/killswitch:killswitch"),
        osquery_target("osquery/killswitch/plugins:filesystem"),
        osquery_target("osquery/killswitch/plugins:tls"),
        osquery_target("osquery/logger:data_logger"),
        osquery_target("osquery/logger/plugins:buffered"),
        osquery_target("osquery/logger/plugins:filesystem"),
        osquery_target("osquery/logger/plugins:stdout"),
        osquery_target("osquery/logger/plugins:syslog"),
        osquery_target("osquery/logger/plugins:tls_logger"),
        osquery_target("osquery/process:process"),
        osquery_target("osquery/numeric_monitoring:numeric_monitoring"),
        osquery_target("osquery/numeric_monitoring/plugins:filesystem"),
        osquery_target("osquery/registry:registry"),
        osquery_target("osquery/remote/enroll:tls_enroll"),
        osquery_target("osquery/sql:sql"),
        osquery_target("specs:tables"),
        osquery_tp_target("boost"),
    ],
)
