#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:platforms.bzl", "LINUX", "MACOSX", "POSIX", "WINDOWS")

osquery_cxx_library(
    name = "tables",
    platform_deps = [
        (
            POSIX,
            [
                osquery_target("osquery/tables/sleuthkit:sleuthkit"),
                osquery_target("osquery/tables/yara:yara"),
                osquery_target("osquery/tables/lldpd:lldpd"),
            ],
        ),
        (
            LINUX,
            [
                osquery_target("osquery/tables/cloud:cloud"),
                osquery_target("osquery/tables/smart:smart"),
            ],
        ),
        (
            MACOSX,
            [
                osquery_target("osquery/tables/cloud:cloud"),
                osquery_target("osquery/tables/smart:smart"),
            ],
        ),
        (
            WINDOWS,
            [
                osquery_target("osquery/tables/cloud:cloud"),
            ],
        ),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/tables/applications:applications"),
        osquery_target("osquery/tables/events:events"),
        osquery_target("osquery/tables/forensic:forensic"),
        osquery_target("osquery/tables/networking:networking"),
        osquery_target("osquery/tables/system:system"),
        osquery_target("osquery/tables/utility:utility"),
    ],
)
