#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:platforms.bzl", "LINUX")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "perf_event",
    header_namespace = "osquery/utils/system/linux/perf_event",
    exported_platform_headers = [
        (
            LINUX,
            [
                "perf_event.h",
            ],
        ),
    ],
    platform_srcs = [
        (
            LINUX,
            [
                "perf_event.cpp",
            ],
        ),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/utils/expected:expected"),
        osquery_target("osquery/utils/system:errno"),
        osquery_tp_target("boost"),
    ],
)
