#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "data_logger",
    srcs = ["logger.cpp"],
    header_namespace = "osquery/logger",
    tests = [
        osquery_target("osquery/logger/tests:logger"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/core/plugins:plugins"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/filesystem:filesystem"),
        osquery_target("osquery/killswitch:killswitch"),
        osquery_target("osquery/numeric_monitoring:numeric_monitoring"),
        osquery_target("osquery/registry:registry"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_target("osquery/utils/info:info"),
        osquery_target("osquery/utils/system:time"),
        ":logger",
    ],
)

osquery_cxx_library(
    name = "logger",
    header_namespace = "osquery",
    exported_headers = [
        "logger.h",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_tp_target("glog"),
    ],
)
