#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

# @generated

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_prebuilt_cxx_library")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_tp_prebuilt_cxx_library(
    name = "libaudit",
    platforms = [
        "linux-x86_64",
    ],
    sha256sums = {
        "linux-x86_64": "4e87a234f68eb8686ab3fa9096ffd664a899efc8e7839c767abd60ac956f6688",
    },
    platform_static_libs = {
        "linux-x86_64": [
            "lib/libaudit.a",
        ],
    },
    linker_flags = [

    ],
    deps = [

    ],
    version = "2.4.2",
    build = "0",
    visibility = ["PUBLIC"],
)
