#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:platforms.bzl", "POSIX")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_test(
    name = "smart_drives_tests",
    platform_srcs = [
        (
            POSIX,
            [
                "smart_drives_tests.cpp",
            ],
        ),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/tables/events:events"),
        osquery_target("osquery/config/parsers:parsers"),
        osquery_target("osquery/config:config"),
        osquery_target("osquery/logger:logger"),
        osquery_target("osquery/registry:registry"),
        osquery_target("osquery:headers"),
        osquery_target("specs:tables"),
        osquery_target("osquery/config/tests:test_utils"),
        osquery_target("osquery/config/plugins:tls_config"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/database/plugins:ephemeral"),
        osquery_target("osquery/extensions:extensions"),
        osquery_target("osquery/remote/enroll:tls_enroll"),
        osquery_target("specs:tables"),
        osquery_tp_target("smartmontools", "libsmartctl"),
    ],
)
