#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_filegroup")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "osquery-cpp2",
    srcs = [
        "gen/Extension.cpp",
        "gen/ExtensionManager.cpp",
        "gen/osquery_constants.cpp",
        "gen/osquery_types.cpp",
    ],
    header_namespace = "",
    exported_headers = {
        "Extension.h": "gen/Extension.h",
        "ExtensionManager.h": "gen/ExtensionManager.h",
        "osquery_constants.h": "gen/osquery_constants.h",
        "osquery_types.h": "gen/osquery_types.h",
    },
    visibility = ["PUBLIC"],
    deps = [
        osquery_tp_target("thrift"),
    ],
)

osquery_filegroup(
    name = "thrift_file",
    srcs = [
        "osquery.thrift",
    ],
    visibility = ["PUBLIC"],
)
