#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "osquery-cpp2",
    srcs = [
        "gen/Extension.cpp",
        "gen/ExtensionManager.cpp",
        "gen/osquery_constants.cpp",
        "gen/osquery_types.cpp",
    ],
    header_namespace = "",
    exported_headers = {
        "Extension.h": "gen/Extension.h",
        "ExtensionManager.h": "gen/ExtensionManager.h",
        "osquery_constants.h": "gen/osquery_constants.h",
        "osquery_types.h": "gen/osquery_types.h",
    },
    visibility = ["PUBLIC"],
    deps = [
        osquery_tp_target("thrift"),
    ],
)
