#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "killswitch",
    srcs = [
        "killswitch.cpp",
        "killswitch_plugin.cpp",
        "killswitch_refreshable_plugin.cpp",
    ],
    header_namespace = "osquery/killswitch",
    exported_headers = [
        "killswitch_plugin.h",
        "killswitch_refreshable_plugin.h",
    ],
    link_whole = True,
    tests = [
        osquery_target("osquery/killswitch/tests:killswitch_tests"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_tp_target("googletest", "gtest_headers"),
    ],
)
