#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:platforms.bzl", "POSIX", "WINDOWS")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "process",
    header_namespace = "osquery/process",
    exported_headers = [
        "process.h",
    ],
    exported_platform_headers = [
        (
            WINDOWS,
            [
                "windows/process_ops.h",
            ],
        ),
    ],
    platform_srcs = [
        (
            POSIX,
            [
                "posix/process.cpp",
                "posix/process_ops.cpp",
            ],
        ),
        (
            WINDOWS,
            [
                "windows/process.cpp",
                "windows/process_ops.cpp",
            ],
        ),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery:headers"),
        osquery_target("osquery/utils/system:env"),
        osquery_tp_target("boost"),
        osquery_tp_target("glibc", "dl"),
    ],
)
