#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:platforms.bzl", "FREEBSD", "LINUX", "MACOSX")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "yara_table",
    srcs = [
        "yara.cpp",
        "yara_utils.cpp",
    ],
    header_namespace = "osquery/tables/yara",
    exported_headers = [
        "yara_utils.h",
    ],
    exported_post_platform_linker_flags = [
        (
            FREEBSD,
            [
                "-lyara",
            ],
        ),
    ],
    link_whole = True,
    platform_srcs = [
        (
            LINUX,
            [
                "yara_events.cpp",
            ],
        ),
        (
            MACOSX,
            [
                "yara_events.cpp",
            ],
        ),
    ],
    tests = [
        osquery_target("osquery/tables/yara/tests:yara_tests"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery:headers"),
        osquery_target("osquery/config:config"),
        osquery_target("osquery/dispatcher:dispatcher"),
        osquery_target("osquery/events:events"),
        osquery_target("osquery/logger:logger"),
        osquery_target("osquery/registry:registry"),
        osquery_target("osquery/utils/config:utils_config"),
        osquery_tp_target("boost"),
        osquery_tp_target("yara"),
    ],
)
