#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "core_sql",
    srcs = glob(["*.cpp"]),
    header_namespace = "osquery/core/sql",
    exported_headers = glob(["*.h"]),
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/utils/json:json"),
        osquery_target("osquery/utils/status:status"),
        osquery_tp_target("sqlite"),
    ],
)
