#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

# @generated

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_prebuilt_cxx_library")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_tp_prebuilt_cxx_library(
    name = "libudev",
    platforms = [
        "linux-x86_64",
    ],
    sha256sums = {
        "linux-x86_64": "fc1483fa27cb92876661e453bceef0c5752e4dbe83074a1653928ce44078aa34",
    },
    platform_static_libs = {
        "linux-x86_64": [
            "lib/libudev.a",
        ],
    },
    linker_flags = [

    ],
    deps = [

    ],
    version = "173",
    build = "0",
    visibility = ["PUBLIC"],
)
