#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "tls_enroll_plugin",
    srcs = [
        "tls_enroll.cpp",
    ],
    header_namespace = "plugins/remote/enroll",
    exported_headers = [
        "tls_enroll.h",
    ],
    tests = [
        osquery_target("plugins/remote/enroll/tests:tls_enroll_tests"),
    ],
    link_whole = True,
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/remote/enroll:tls_enroll"),
    ],
)
