#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "plugin_sdk",
    srcs = [
        "empty_register_foreign_tables.cpp",
    ],
    header_namespace = "osquery/sdk",
    exported_headers = [
        "plugin_sdk.h",
        "sdk.h",
    ],
    link_whole = True,
    tests = [
        osquery_target("osquery/sdk/tests:plugin_sdk_tests"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery:headers"),
        osquery_target("osquery/config:config"),
        osquery_target("osquery/dispatcher:dispatcher"),
        osquery_target("osquery/events:events_registry"),
        osquery_target("osquery/experimental/events_stream:events_stream_registry"),
        osquery_target("osquery/extensions:extensions"),
        osquery_target("osquery/killswitch:killswitch"),
        osquery_target("osquery/numeric_monitoring:numeric_monitoring"),
        osquery_target("osquery/remote/enroll:tls_enroll"),
        osquery_target("osquery/sql:sql"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_target("osquery/utils/debug:debug"),
        osquery_target("osquery/utils/expected:expected"),
        osquery_target("osquery/utils/info:info"),
        osquery_target("osquery/utils/macros:macros"),
        osquery_target("osquery/utils/status:status"),
        osquery_target("osquery/utils/system:env"),
        osquery_target("osquery/utils/system:errno"),
        osquery_target("osquery/utils/system:filepath"),
        osquery_target("osquery/utils/system:system_utils"),
        osquery_target("osquery/utils/system:time"),
        osquery_target("osquery/utils/system:uptime"),
        osquery_target("osquery/utils:attribute"),
        osquery_target("osquery/utils:utils"),
        osquery_target("plugins/database:ephemeral"),
    ],
)
