#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "filesystem",
    srcs = [
        "filesystem.cpp",
    ],
    header_namespace = "osquery/numeric_monitoring/plugins",
    exported_headers = [
        "filesystem.h",
    ],
    tests = [
        osquery_target("osquery/numeric_monitoring/plugins/tests:filesystem"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/filesystem:filesystem"),
        osquery_target("osquery/numeric_monitoring:numeric_monitoring"),
    ],
)
