#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under both the Apache 2.0 license (found in the
#  LICENSE file in the root directory of this source tree) and the GPLv2 (found
#  in the COPYING file in the root directory of this source tree).
#  You may select, at your option, one of the above-listed licenses.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "plugins",
    srcs = glob(["*.cpp"]),
    headers = glob(["*.h"]),
    header_namespace = "osquery/plugins",
    exported_headers = glob(["*.h"]),
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core/sql:sql"),
        osquery_target("osquery/utils/json:json"),
        osquery_target("osquery/utils/status:status"),
    ],
)
