#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "plugins",
    srcs = glob(["*.cpp"]),
    header_namespace = "osquery/plugins",
    exported_headers = glob(["*.h"]),
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core/sql:core_sql"),
        osquery_target("osquery/utils/json:json"),
        osquery_target("osquery/utils/status:status"),
    ],
)
