#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "dispatcher",
    srcs = [
        "dispatcher.cpp",
        "distributed_runner.cpp",
        "scheduler.cpp",
    ],
    header_namespace = "osquery/dispatcher",
    exported_headers = [
        "distributed_runner.h",
        "scheduler.h",
    ],
    tests = [
        osquery_target("osquery/dispatcher/tests:dispatcher_tests"),
        osquery_target("osquery/dispatcher/tests:scheduler"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/logger:data_logger"),
        osquery_target("osquery/process:process"),
        osquery_target("osquery/profiler:profiler"),
        osquery_target("osquery/sql:sql"),
        osquery_target("osquery/utils:utils"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_target("plugins/config/parsers:parsers"),
        osquery_tp_target("googletest", "gtest_headers"),
    ],
)
