#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "numeric_monitoring",
    srcs = [
        "numeric_monitoring.cpp",
        "plugin_interface.cpp",
        "pre_aggregation_cache.cpp",
    ],
    header_namespace = "osquery/numeric_monitoring",
    exported_headers = [
        "plugin_interface.h",
        "pre_aggregation_cache.h",
    ],
    tests = [
        osquery_target("osquery/numeric_monitoring/tests:numeric_monitoring_tests"),
        osquery_target("osquery/numeric_monitoring/tests:pre_aggregation_cache"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/utils:utils"),
        osquery_tp_target("boost"),
    ],
)
