#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "database",
    srcs = [
        "database.cpp",
    ],
    header_namespace = "osquery/database",
    exported_headers = [
    ],
    tests = [
        osquery_target("osquery/database/tests:database_tests"),
        osquery_target("osquery/database/tests:results"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/utils:utils"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_tp_target("boost"),
    ],
    exported_deps = [
    ],
)
