#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed in accordance with the terms specified in
#  the LICENSE file found in the root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "hostname",
    srcs = [
        "hostname.cpp",
    ],
    header_namespace = "osquery/system/network",
    exported_headers = [
        "hostname.h",
    ],
    tests = [
        osquery_target("osquery/system/network/tests:hostname_host_identity_tests"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/utils/schemer:schemer"),
        osquery_target("osquery/utils/status:status"),
    ],
)
