#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_test(
    name = "semantic_version_test",
    srcs = [
        "semantic.cpp",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/utils/versioning:semantic"),
    ],
)
