load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_test(
    name = "aws",
    srcs = [
        "aws_util_tests.cpp",
    ],
    env = {
        "TEST_CONF_FILES_DIR": "$(location {})".format(
            osquery_target("tools/tests:aws_files"),
        ),
    },
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/config/plugins:tls_config"),
        osquery_target("osquery/config/tests:test_utils"),
        osquery_target("osquery/database/plugins:ephemeral"),
        osquery_target("osquery/dispatcher:dispatcher"),
        osquery_target("osquery/events:events"),
        osquery_target("osquery/extensions:extensions"),
        osquery_target("osquery/process:process"),
        osquery_target("osquery/remote/enroll:tls_enroll"),
        osquery_target("osquery/utils/aws:aws"),
        osquery_target("osquery/utils/info:info"),
        osquery_target("specs:tables"),
    ],
)
