//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DMAPFS : NSObject
{
    id _instPriv;
}

- (int)isVMVolume:(struct __DADisk *)arg1 vmRole:(char *)arg2;
- (int)isRecoveryVolume:(struct __DADisk *)arg1 recoveryRole:(char *)arg2;
- (int)isSystemVolume:(struct __DADisk *)arg1 systemRole:(char *)arg2;
- (int)isUserVolume:(struct __DADisk *)arg1 userRole:(char *)arg2;
- (int)isPrebootVolume:(struct __DADisk *)arg1 prebootRole:(char *)arg2;
- (int)isEffacableVolume:(struct __DADisk *)arg1 effaceable:(char *)arg2 only:(char *)arg3;
- (int)isEncryptedVolume:(struct __DADisk *)arg1 encrypted:(char *)arg2;
- (int)capacityQuotaForVolume:(struct __DADisk *)arg1 quotaOrNull:(id *)arg2;
- (int)capacityReserveForVolume:(struct __DADisk *)arg1 reserveOrNull:(id *)arg2;
- (int)capacityInUseForVolume:(struct __DADisk *)arg1 used:(id *)arg2;
- (int)isFusionContainer:(struct __DADisk *)arg1 fusion:(char *)arg2;
- (int)capacityFreeForContainer:(struct __DADisk *)arg1 free:(id *)arg2;
- (int)capacityCeilingForContainer:(struct __DADisk *)arg1 size:(id *)arg2;
- (int)volumeForVolumeUUID:(id)arg1 volume:(struct __DADisk **)arg2;
- (int)volumeUUIDForVolume:(struct __DADisk *)arg1 UUID:(id *)arg2;
- (int)physicalStoreForPhysicalStoreUUID:(id)arg1 physicalStore:(struct __DADisk **)arg2;
- (int)physicalStoreUUIDForPhysicalStore:(struct __DADisk *)arg1 UUID:(id *)arg2;
- (int)containerForContainerUUID:(id)arg1 container:(struct __DADisk **)arg2;
- (int)containerUUIDForContainer:(struct __DADisk *)arg1 UUID:(id *)arg2;
- (int)snapshotForMountPoint:(id)arg1 name:(id *)arg2 volume:(struct __DADisk **)arg3 container:(struct __DADisk **)arg4;
- (int)containerForVolume:(struct __DADisk *)arg1 container:(struct __DADisk **)arg2;
- (int)containerForPhysicalStore:(struct __DADisk *)arg1 container:(struct __DADisk **)arg2;
- (int)mountPointForSnapshot:(id)arg1 forVolume:(struct __DADisk *)arg2 mountPoint:(id *)arg3;
- (int)snapshotsForVolume:(struct __DADisk *)arg1 names:(id *)arg2;
- (int)containerSchemeDiskForContainer:(struct __DADisk *)arg1 schemeDisk:(struct __DADisk **)arg2;
- (int)volumesForContainer:(struct __DADisk *)arg1 volumes:(id *)arg2;
- (int)physicalStoresForContainer:(struct __DADisk *)arg1 physicalStores:(id *)arg2;
- (int)containers:(id *)arg1;
- (int)setRoleForVolume:(struct __DADisk *)arg1 options:(id)arg2;
- (int)eraseVolume:(struct __DADisk *)arg1 newFilesystem:(id)arg2 newName:(id)arg3 options:(id)arg4;
- (int)deleteVolume:(struct __DADisk *)arg1 options:(id)arg2;
- (int)addVolumeToContainer:(struct __DADisk *)arg1 newFilesystem:(id)arg2 newName:(id)arg3 options:(id)arg4;
- (int)resizeContainerByPhysicalStore:(struct __DADisk *)arg1 newPhysicalStoreSize:(id)arg2 newMapEntries:(id)arg3 options:(id)arg4;
- (int)deleteContainer:(struct __DADisk *)arg1 reformatToNewNames:(id)arg2 options:(id)arg3;
- (int)createContainerFromDisks:(id)arg1 options:(id)arg2;
- (void)dealloc;
- (id)initWithManager:(id)arg1;
- (id)init;

@end
