#  Copyright (c) 2014-present, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed as defined on the LICENSE file found in the
#  root directory of this source tree.

load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "json",
    srcs = [
        "json.cpp",
    ],
    header_namespace = "osquery/utils/json",
    exported_headers = [
        "json.h",
    ],
    exported_preprocessor_flags = [
        "-DRAPIDJSON_HAS_STDSTRING=1",
    ],
    tests = [":json_tests"],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/utils:utils"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_target("osquery/utils/status:status"),
        osquery_target("osquery/utils/system:system_utils"),
        osquery_tp_target("rapidjson"),
    ],
)

osquery_cxx_test(
    name = "json_tests",
    srcs = [
        "tests/json.cpp",
    ],
    visibility = ["PUBLIC"],
    deps = [
        ":json",
    ],
)
